version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "terraform"
    directory: "/terraform/envs/prod"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "terraform"

  - package-ecosystem: "docker"
    directory: "/src/app001-api"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
